version: '3.0'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: test123
  wordpress:
   depends_on:
    - db
   image: wordpress
   ports:
      - "8080:80"
   restart: always
   environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: test123
      WORDPRESS_DB_NAME: wordpress
